import React, { useEffect } from "react";
import { useParams } from "react-router-dom";

// mui material
import { CircularProgress, Container, Grid } from "@mui/material";

// styles
import classes from "./_SummaryTest.module.scss";

// redux
import { useDispatch, useSelector } from "react-redux";
import { getChildrenSummaryTest } from "../../../../../store/profilingTest/getChildrenSummaryTest";

// helper
import { API_FETCH_STATUS } from "../../../../../constants/api";

// assets
import { ReactComponent as NoGeneratedSummary } from "../../../../../assets/images/ChildrenDashboard/summary-test/illustration-generate-summary.svg";
import { ReactComponent as TransparentPlanet } from "../../../../../assets/images/transparent-planet.svg";

// components
import FooterSummaryTest from "./components/FooterSummaryTest";
import KeyLearningDimensionSection from "./components/KeyLearningDimensionSection";
import MultipleIntelligence from "./components/MultipleIntelligence";
import PersonalTypologySection from "./components/PersonalTypologySection";
import SensorySection from "./components/SensorySection";

// dummy
import CareerInterestSection from "./components/CareerInterestSection";

const SummaryTest = () => {
  const dispatch = useDispatch();
  const { childrenId, referenceId } = useParams();

  const {
    summaryResults: summaryResultsData,
    status,
    statusCode,
    resultReferenceId,
  } = useSelector((store) => store.resChildrenSummaryTest);

  useEffect(() => {
    // TODO implement if done new json response
    if (
      status === API_FETCH_STATUS.IS_IDLE ||
      resultReferenceId !== referenceId
    ) {
      dispatch(getChildrenSummaryTest({ childrenId, referenceId }));
    }
  }, []);

  const { mbti, kld, mi, sensory, career } = summaryResultsData || {};

  if (status === API_FETCH_STATUS.IS_LOADING) {
    return (
      <Grid
        container
        justifyContent="center"
        alignContent="center"
        sx={{ height: "100vh", color: "#7966FA" }}
      >
        <CircularProgress color="inherit" />
      </Grid>
    );
  }

  if (status !== API_FETCH_STATUS.IS_LOADING && statusCode !== 200) {
    return (
      <Grid
        container
        justifyContent="center"
        alignItems="center"
        direction="column"
        gap={2}
        className={classes.illustrationContainer}
      >
        <NoGeneratedSummary className={classes.illustrationImage} />
        <h6>Summary is being generated...</h6>
        <div>
          <p>Please wait for a second, your summary is being</p>
          <p>generated by the system.</p>
        </div>
      </Grid>
    );
  }

  return (
    <div className={classes.containerSummaryTestPage}>
      <TransparentPlanet className={classes.transparentPlanetBG} />

      <Container maxWidth="lg">
        <div className={classes.subscribeContainer}>
          <div className={classes.contentSubscribe}>
            <p>YOUR GRIP LEARNING PROFILE</p>
            <h5>SUMMARY</h5>
          </div>
        </div>

        <div className={classes.summaryTestContainer}>
          {mbti && (
            <PersonalTypologySection
              score={mbti?.score}
              content={mbti?.content}
            />
          )}

          {kld && (
            <KeyLearningDimensionSection
              score={kld.score}
              content={kld.content}
            />
          )}

          {mi && (
            <MultipleIntelligence score={mi?.score} content={mi?.content} />
          )}

          {sensory && (
            <SensorySection score={sensory.score} content={sensory.content} />
          )}

          {career && (
            <CareerInterestSection
              score={career?.score}
              content={career?.content}
            />
          )}
        </div>
      </Container>
      <FooterSummaryTest />
    </div>
  );
};

export default SummaryTest;
