import React, { Fragment, useEffect } from "react";
import { useParams } from "react-router-dom";

// Redux
import { useDispatch, useSelector } from "react-redux";
import { getChildrenSummaryTest } from "../../../../store/profilingTest/getChildrenSummaryTest";

// MUI
import { Container, Grid, Typography } from "@mui/material";

// Components
import Preloader from "../../../../components/preloader/Preloader";
import CareerInterestSection from "./components/CareerInterestSection";
import KeyLearningDimensionSection from "./components/KeyLearningDimensionSection";
import MultipleIntelligenceSection from "./components/MultipleIntelligenceSection";
import PersonalTypologySection from "./components/PersonalTypologySection";
import SensorySection from "./components/SensorySection";
import SummaryTestFooter from "./components/SummaryTestFooter";
import SummaryTestHeader from "./components/SummaryTestHeader";

// Helper
import { API_FETCH_STATUS } from "../../../../constants/api";

// Styles
import classes from "./_SummaryTest.module.scss";

// Assets
import { ReactComponent as GenerateSummaryIllustration } from "../../../../assets/images/ChildrenDashboard/summary-test/illustration-generate-summary.svg";

const SummaryTest = () => {
  const dispatch = useDispatch();
  const { childrenId, referenceId } = useParams();

  // #redux state
  const {
    summaryResults: summaryResultsData,
    status,
    statusCode,
  } = useSelector((store) => store.resChildrenSummaryTest);
  // #endregion

  // #region useEffect
  useEffect(() => {
    dispatch(getChildrenSummaryTest({ childrenId, referenceId }));
    window.scrollTo(0, 0);
  }, []);
  // #endregion

  // #region variable
  const { mbti, kld, mi, sensory, career } = summaryResultsData || {};
  const isFetching = status === API_FETCH_STATUS.IS_LOADING;
  const summaryIsBeingGenerated = statusCode === 422 || status === null;
  // #endregion

  if (isFetching) return <Preloader />;

  return (
    <Fragment>
      <SummaryTestHeader />
      <Container className={classes.container}>
        <Grid container flexDirection="column" gap={2}>
          {summaryIsBeingGenerated ? (
            <Grid container className={classes.loadingContainer}>
              <Grid>
                <GenerateSummaryIllustration />
                <Typography className={classes.title}>
                  Summary is being generated...
                </Typography>
                <Typography className={classes.subtitle}>
                  Please wait for a second, your summary is being generated by
                  the system.
                </Typography>
              </Grid>
            </Grid>
          ) : (
            <Fragment>
              <Grid className={classes.summaryHeaderContainer}>
                <Grid container className={classes.backgroundCover}>
                  <Typography className={classes.summarySubtitle}>
                    YOUR GRIP LEARNING PROFILE
                  </Typography>
                  <Typography className={classes.summaryTitle}>
                    SUMMARY
                  </Typography>
                </Grid>
              </Grid>
              <PersonalTypologySection data={mbti} />
              <KeyLearningDimensionSection data={kld} />
              <MultipleIntelligenceSection data={mi} />
              <SensorySection data={sensory} />
              <CareerInterestSection data={career} />
            </Fragment>
          )}
          <SummaryTestFooter />
        </Grid>
      </Container>
    </Fragment>
  );
};

export default SummaryTest;
